const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_19_55_10_17_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNjcsXG4gICAgICAgIDI1NCxcbiAgICAgICAgOTEsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjI2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMzAsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjM0LFxuICAgICAgICA3NyxcbiAgICAgICAgMjM5LFxuICAgICAgICAxMDMsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjM5LFxuICAgICAgICA2MixcbiAgICAgICAgMixcbiAgICAgICAgNzksXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTEzLFxuICAgICAgICA1NSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNDIsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTE0LFxuICAgICAgICA4NixcbiAgICAgICAgMTY2LFxuICAgICAgICAxMSxcbiAgICAgICAgMjQ0LFxuICAgICAgICA4MFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjE5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxODUsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTQsXG4gICAgICAgIDksXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNDksXG4gICAgICAgIDIyOCxcbiAgICAgICAgMjM1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTY2LFxuICAgICAgICA2MyxcbiAgICAgICAgMTMxLFxuICAgICAgICAzNSxcbiAgICAgICAgMyxcbiAgICAgICAgMTcyLFxuICAgICAgICAxODUsXG4gICAgICAgIDcxLFxuICAgICAgICAyNTEsXG4gICAgICAgIDI3LFxuICAgICAgICAyMDQsXG4gICAgICAgIDEzLFxuICAgICAgICA3NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICA4LFxuICAgICAgICAxNDEsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTgsXG4gICAgICAgIDUyLFxuICAgICAgICAyMjUsXG4gICAgICAgIDc3LFxuICAgICAgICAyMTksXG4gICAgICAgIDk4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTE2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNjYsXG4gICAgICAgIDExNixcbiAgICAgICAgMzQsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTM5LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE5MCxcbiAgICAgICAgODIsXG4gICAgICAgIDk3LFxuICAgICAgICAyNTEsXG4gICAgICAgIDcyLFxuICAgICAgICAxNjcsXG4gICAgICAgIDk4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgOTEsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTEwLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMSxcbiAgICAgICAgMTgxLFxuICAgICAgICAxMDUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjE5LFxuICAgICAgICA2MSxcbiAgICAgICAgMzUsXG4gICAgICAgIDUwLFxuICAgICAgICAzNSxcbiAgICAgICAgOTAsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTE3LFxuICAgICAgICAyNDcsXG4gICAgICAgIDIyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIwNixcbiAgICAgICAgODEsXG4gICAgICAgIDEwOSxcbiAgICAgICAgNDUsXG4gICAgICAgIDExMixcbiAgICAgICAgNjdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3NixcbiAgICAgICAgMTY1LFxuICAgICAgICAxNjUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDcxLFxuICAgICAgICAxMTIsXG4gICAgICAgIDI4LFxuICAgICAgICAxMTksXG4gICAgICAgIDQ5LFxuICAgICAgICAzMCxcbiAgICAgICAgMjE1LFxuICAgICAgICA3MyxcbiAgICAgICAgMjcsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTMxLFxuICAgICAgICAxMjMsXG4gICAgICAgIDE0LFxuICAgICAgICAxMTAsXG4gICAgICAgIDQyLFxuICAgICAgICA3MSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNDEsXG4gICAgICAgIDM5LFxuICAgICAgICAyNTEsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTQsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMjFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI1LFxuICAgICAgICA2OSxcbiAgICAgICAgMTM2LFxuICAgICAgICA2LFxuICAgICAgICAxMjYsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyMTQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTU2LFxuICAgICAgICA0OSxcbiAgICAgICAgMTkzLFxuICAgICAgICA1MyxcbiAgICAgICAgODYsXG4gICAgICAgIDIxOSxcbiAgICAgICAgNzIsXG4gICAgICAgIDMyLFxuICAgICAgICA3MixcbiAgICAgICAgMjI0LFxuICAgICAgICA2OCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTc2LFxuICAgICAgICA0MixcbiAgICAgICAgNDYsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTQsXG4gICAgICAgIDEyLFxuICAgICAgICAxNzUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMzVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDEwNFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA2MyxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA0NCxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICA1MixcbiAgICAgICAgICA4NyxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA2MixcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMTI3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMsXG4gICAgICAgIDgxLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxMDMsXG4gICAgICAgIDk0LFxuICAgICAgICAxNTQsXG4gICAgICAgIDgxLFxuICAgICAgICA3NSxcbiAgICAgICAgNTYsXG4gICAgICAgIDExMSxcbiAgICAgICAgMzAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNTQsXG4gICAgICAgIDI2LFxuICAgICAgICA2MyxcbiAgICAgICAgMjcsXG4gICAgICAgIDk0LFxuICAgICAgICAxMjYsXG4gICAgICAgIDU3LFxuICAgICAgICAwLFxuICAgICAgICAyNixcbiAgICAgICAgMjEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNTUsXG4gICAgICAgIDc1LFxuICAgICAgICAxODksXG4gICAgICAgIDE5MyxcbiAgICAgICAgNDcsXG4gICAgICAgIDEzNCxcbiAgICAgICAgODQsXG4gICAgICAgIDE0LFxuICAgICAgICA4OCxcbiAgICAgICAgMzMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgOCxcbiAgICAgICAgOCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMDcsXG4gICAgICAgIDYzLFxuICAgICAgICA1MSxcbiAgICAgICAgMTM2LFxuICAgICAgICAxNyxcbiAgICAgICAgNjksXG4gICAgICAgIDE5LFxuICAgICAgICAxNTgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjI1LFxuICAgICAgICA3NyxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMDgsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTc1LFxuICAgICAgICA4MixcbiAgICAgICAgMTMxLFxuICAgICAgICAwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDcsXG4gICAgICAgIDEwNSxcbiAgICAgICAgNDksXG4gICAgICAgIDIwMixcbiAgICAgICAgMTM0XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxOTUsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiZk5hU1E0TCtwNFZVbSt0TWlQTlQvUk56cTJxNjIzUkwrb0dsUXZIZjZHUT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMyMzcwNDU5MTlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkM4OTU3OTg2NTUxQTc0NkY2OUEwNDY2RTQwODQxOTQ2XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyOTE5NDkzNVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCI5Wk1COEFhQVEyV3RKaEZLRGtHVmJ3XCIsXG4gIFwicGhvbmVJZFwiOiBcImY4NGNkMGZiLTExMDAtNDU1YS05NWNmLTMzYjg1NGE0NzZhN1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAzNixcbiAgICAgIDIxNixcbiAgICAgIDQsXG4gICAgICAyMjYsXG4gICAgICAyNDEsXG4gICAgICAyNDMsXG4gICAgICAwLFxuICAgICAgOTMsXG4gICAgICAxNDEsXG4gICAgICAyNTMsXG4gICAgICAyMTcsXG4gICAgICAxODMsXG4gICAgICAxNDUsXG4gICAgICAyNDksXG4gICAgICA1OCxcbiAgICAgIDE1LFxuICAgICAgMjU0LFxuICAgICAgNSxcbiAgICAgIDExOCxcbiAgICAgIDIwNFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1MSxcbiAgICAgIDEzMixcbiAgICAgIDUxLFxuICAgICAgMTM1LFxuICAgICAgMjMsXG4gICAgICAyNDcsXG4gICAgICAxNDMsXG4gICAgICAyMDksXG4gICAgICA3NCxcbiAgICAgIDYsXG4gICAgICAyMTYsXG4gICAgICAyOCxcbiAgICAgIDIyOSxcbiAgICAgIDYzLFxuICAgICAgNzYsXG4gICAgICAxOCxcbiAgICAgIDI0MyxcbiAgICAgIDE0MixcbiAgICAgIDYsXG4gICAgICAxMDJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiMlFGWDMyWFdcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzIzNzA0NTkxOTo2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiQXJzbGFuTUQg4oiaXCIsXG4gICAgXCJsaWRcIjogXCIxMzEwNjU3NDIxMjcyMzQ6NkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNKeWF6TEFGRUs3WHhiZ0dHQVlnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInF1WlpDN3drUnNyZGdyRCtrSTdObzhkWVVSUmpac2RseDFocGxmVGxuQnM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiQTFLd1YwZExrMWhSbEVwWnZnL2k1RjJYM3N0WWxNUFdXVG54eFRCSWZkZG5taFdNWGZPMGhlV3hwK0RoeHNmZ3NOZk5kanQvRUFkc09ONEhLdHZRRHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiK3hBRjV3UFRqZjJpa3RHZkFOeUgyZGlnaE5rcVhTT0hoQWdIUk55ZE16S3FTM25vaXo2SE9rRmNUYXplRS8ydk03S0x1STFOdEpvUGlQSVIyUFhJaGc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMjM3MDQ1OTE5OjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAzNixcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgODgsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMjdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyOTE5NDkyOSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQURLU1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBREtTLmpzb24iOiAie1wia2V5RGF0YVwiOlwiVFYxclltTTZ4dCsxUjAzYmM3ZTB0d2xuSm5nRkVkZFBZRUFnT0ZnTXErUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDQ0MDg5MTE2LFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjkwODMxMjMzNzBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
